// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Kafka_util_instanceof = require("./Kafka_util_instanceof.bs.js");

var Client = {};

var ProduceRequest = {};

var Producer = {
  ProduceRequest: ProduceRequest
};

var Payload = {};

var MakeOptions = {};

function bufferValue(message) {
  return Kafka_util_instanceof.bufferGetExn(message.value);
}

var Consumer = {
  Payload: Payload,
  MakeOptions: MakeOptions,
  bufferValue: bufferValue
};

var OffsetRequest = {};

var OffsetCommitRequest = {};

var Offset = {};

exports.Client = Client;
exports.Producer = Producer;
exports.Consumer = Consumer;
exports.OffsetRequest = OffsetRequest;
exports.OffsetCommitRequest = OffsetCommitRequest;
exports.Offset = Offset;
/* Kafka_util_instanceof Not a pure module */
