// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var DynamicCastError = /* @__PURE__ */Caml_exceptions.create("Kafka_util_instanceof.DynamicCastError");

function myinstanceof(c, x) { return x instanceof c }
;

function $$instanceof(c, x) {
  return myinstanceof(c, x);
}

var bufferConstructor = Buffer;

function instanceofBuffer(x) {
  return $$instanceof(bufferConstructor, x);
}

function maybeBuffer(x) {
  if (instanceofBuffer(x)) {
    return Caml_option.some(x);
  }
  
}

function bufferGetExn(x) {
  if (instanceofBuffer(x)) {
    return x;
  }
  throw {
        RE_EXN_ID: DynamicCastError,
        Error: new Error()
      };
}

exports.$$instanceof = $$instanceof;
exports.instanceofBuffer = instanceofBuffer;
exports.maybeBuffer = maybeBuffer;
exports.bufferGetExn = bufferGetExn;
/*  Not a pure module */
